"""電商產品圖的文案與版位資料。

內容照 Claude Design 專案「電商產品圖製作」的 電商產品圖.dc.html，涵蓋設計稿全部
21 項產品、58 張圖卡，數字一律回頭對過實體包裝照與 `lib/data.ts`。與設計稿不同之
處只有一處：設計稿把 DEFENSE 的 `company` 寫成「國鼎生物科技有限公司」，實際是
「圓鼎」（包裝、data.ts 與店家三方一致，2026-08-18 由店家確認）。

設計稿的主圖沒有底板，這裡沿用前八項的作法把去背圖放進圓角淡色版位；`hero_h`
取設計稿 `<img>` 的 max-height，素材到位後仍要看一次成品再微調。

第 9～21 項的 `hero` / `usp_art` / `ing_art` 已指向素材 key，但檔案還沒進
`.tmp/ecom-assets/`；版型會畫出明顯的缺件標記，不會靜默輸出空白圖。
"""

from __future__ import annotations

# 缺件標記用的說明文字。素材備妥就不會用到 —— 前三個 key 已到位，留著是因為
# build script 用這份清單在收尾列出還缺哪幾張，key 移掉就等於失去那道保險。
MISSING_NOTE = {
    "defense-back": "缺 Defense 背面標示照",
    "yi-back": "缺 憶元素 營養標示照",
    "aob": "缺 AOB 商品照",
    "kurozu": "缺 東洋 熟成黑酢膠囊 商品照",
    "biostand": "缺 BIO-STAND 挺液鈣 液態鈣 商品照",
    "congshen": "缺 聰身景麴 商品照",
    "richingsheng": "缺 賢士 日清勝 口服益生菌 商品照",
    "guguanjian": "缺 固關鍵 UC II 膠囊 商品照",
    "jinguguanjian": "缺 TERYLEAF 金固關健 緩釋錠 商品照",
    "youweining": "缺 佑衛寧 高麗菜濃縮複方膠囊 商品照",
    "glutamine": "缺 賜利康 左旋麩醯胺酸 L-GLUTAMINE 商品照",
    "mg": "缺 優全生技 新優力超級鎂 Mg SOD+3 商品照",
    "arginine": "缺 L-Arginine 一氧化氮 素食膠囊 商品照",
    "guerhgan": "缺 中美醫藥 顧爾肝 護肝片 商品照",
    "sbenlin": "缺 益聖靈-P 軟膠囊 SBENLIN-P 商品照",
    "maca": "缺 歐業製藥 勁勇 MEN'S MACA 軟膠囊 商品照",
}

PRODUCTS = [
    {
        "slug": "defense",
        "accent": "#4d7c2a",
        "accent_deep": "#2f5417",
        "bar": "linear-gradient(90deg,#3d6420,#6ea23c,#e2953a)",
        "wash": "radial-gradient(closest-side,#f2f7ea,#ffffff)",
        "chip_bg": "#eef4e4",
        "eyebrow": "PUREGPS® 系列",
        "eyebrow_r": "植物膠囊・全素",
        "title": '強抗力優<sup>®</sup> 450⁺ 膠囊',
        "subtitle": "DEFENSE 450⁺ · β-1,3/1,6 GLUCO POLYSACCHARIDE",
        "hero": "defense-front",
        "hero_w": "600px",
        "chips": [
            ("60粒/盒・每粒450mg", "#eef4e4", "#2f5417"),
            ("Wellmune WGP® 原料", "#eef4e4", "#2f5417"),
            ("FDA APPROVED", "#fdf1e2", "#8a5410"),
        ],
        "usp_art": "defense-front",
        "usp_art_w": "360px",
        "usp_tag": "DEFENSE 450⁺",
        "usp": [
            ("高純度多醣體", "專利技術純化酵母，β-1,3/1,6 長鏈酵母葡聚多醣體純度高達 75% 以上"),
            ("國際原料授權", "採用 Wellmune WGP®，屬 Kerry 公司原料授權使用"),
            ("國際獲獎配方", "榮獲 2007 年 IFT 美國食品科學學會「創新研究獎」"),
            ("每天 1 顆，輕鬆保養", "每顆膠囊含 400mg β-1,3/1,6 酵母葡聚多醣體，天天食用防護周到"),
        ],
        "ing_row_pad": "17px",
        "ing_title": "成分與規格",
        "ing_tag": "每粒 450mg",
        "ing": [
            ("非水溶性葡聚多醣體", "250mg", False),
            ("水溶性葡聚多醣體", "150mg", False),
            ("穀胱甘肽", "50mg", False),
            ("植物膠囊基底", "纖維素・鹿角菜膠・氯化鉀", True),
            ("規格", "每盒 60 粒", True),
            ("產地", "台灣", True),
        ],
        "ing_art": "defense-back",
        "ing_art_bg": "#f6f7f4",
        "note_bg": "#eef4e4",
        "note_fg": "#2f5417",
        "note_body_fg": "#3d5227",
        "note_h": "食用方法",
        "note_p": "每日 1~2 粒，餐後食用。請保存於陰涼乾燥處，避免熱及陽光直射。",
        "company": "圓鼎生物科技有限公司",
        "disclaimer": "注意事項：孕婦及授乳中婦女請遵照醫師指示食用；對穀胱甘肽過敏者、孕婦、哺乳婦女及嬰幼兒應避免食用。",
    },
    {
        "slug": "aob",
        "accent": "#3a8a7a",
        "accent_deep": "#23695c",
        "bar": "linear-gradient(90deg,#23695c,#6cc4b2,#b08d4f)",
        "wash": "radial-gradient(closest-side,#e9f6f2,#ffffff)",
        "chip_bg": "#e7f5f1",
        "eyebrow": "NEW · VITALITY BEAUTY",
        "eyebrow_r": "條狀隨身包",
        "title": "New AOB Vitality Beauty",
        "subtitle": "健全體調・美容增進",
        "hero": "aob",
        "hero_w": "560px",
        "chips": [
            ("45包/盒", "#e7f5f1", "#23695c"),
            ("鋁袋條狀隨身包", "#e7f5f1", "#23695c"),
            ("NEW 配方", "#f5efe2", "#7c6230"),
        ],
        "usp_art": "aob",
        "usp_art_w": "400px",
        "usp_tag": "AOB",
        "usp_title": "產品特色與規格",
        "usp": [
            ("健全體調", "以日常保養為本，做好每天的健康打底"),
            ("美容增進", "內外兼顧，同時照顧美容保養需求"),
            ("45 包條狀隨身包", "單包分裝、免量取，通勤外出輕鬆帶著走"),
        ],
        "spec_table": [
            ("品名", "New AOB Vitality Beauty"),
            ("內容量", "45 包/盒"),
            ("包裝形式", "鋁袋條狀隨身包"),
        ],
        "screens": ["main", "usp"],
    },
    {
        "slug": "elgucare",
        "accent": "#24418f",
        "accent_deep": "#16295c",
        "bar": "linear-gradient(90deg,#16295c,#24418f,#bd2f28)",
        "wash": "radial-gradient(closest-side,#eef1f9,#ffffff)",
        "chip_bg": "#eaeff9",
        "eyebrow": "LHBcare® 綠杏",
        "eyebrow_r": "全素可食",
        "title": '綠杏 益固康<sup>®</sup> 膠囊',
        "subtitle": "ELGUCARE® · NEW TECHNIQUES OF NATURAL HERBAL FORMULAS",
        "hero": "elgucare-hero",
        "hero_h": "520px",
        "chips": [
            ("瓶裝 360粒", "#eaeff9", "#16295c"),
            ("盒裝 72粒・每粒600mg", "#eaeff9", "#16295c"),
            ("全素可食", "#e9f3e6", "#2f6323"),
            ("產地台灣", "#f9ecea", "#8c231e"),
        ],
        "usp_art": "elgucare-bottle",
        "usp_art_w": "340px",
        "usp_tag": "ELGUCARE®",
        "usp": [
            ("中醫藥專家研製", "集多年經驗，依人體生理機能需要特別研製的保健配方"),
            ("八種草本萃取複方", "黃耆・紅棗・丹參・雞屎藤・伸筋草・玉竹・紅景天・甘草"),
            ("生活挺立、能量豐沛", "日常保健，可讓生活挺立、豐沛人體能量"),
            ("全素可食", "素食者可安心食用，兩種容量規格自由選擇"),
        ],
        "ing_title": "成分與建議用量",
        "ing_tag": "每粒 600mg",
        "ing": [
            ("黃耆萃取", "210mg", False),
            ("紅棗萃取", "100mg", False),
            ("丹參萃取", "45mg", False),
            ("雞屎藤萃取", "35mg", False),
            ("伸筋草萃取", "35mg", False),
            ("玉竹萃取", "35mg", False),
            ("紅景天萃取", "20mg", False),
            ("甘草萃取", "20mg", False),
        ],
        "ing_art": "elgucare-box",
        "ing_art_bg": "#f5f6f8",
        "note_bg": "#eaeff9",
        "note_fg": "#16295c",
        "note_body_fg": "#2c3a5e",
        "note_h": "建議用量",
        "note_p": "保健：每日 2 次，每次 1~2 粒<br>加強：每日 2 次，每次 2~3 粒<br>飯前空腹食用最佳，多食無益",
        "company": "綠杏生物科技有限公司 總經銷",
        "disclaimer": "注意事項：避免孩童自行取用，請置於陰涼處、避免陽光直射。產地：台灣｜",
    },
    {
        "slug": "yiyuansu",
        "accent": "#b87c08",
        "accent_deep": "#7c5606",
        "bar": "linear-gradient(90deg,#b87c08,#eab52c,#2c4a9e)",
        "wash": "radial-gradient(closest-side,#fdf4dc,#ffffff)",
        "chip_bg": "#fdf3da",
        "eyebrow": "天麻100膠囊 · 食品",
        "eyebrow_r": "SGS 檢驗合格",
        "title": "憶元素 天麻100膠囊",
        "subtitle": "TIANMA 100 CAPSULES · 龍眼花+天麻雙萃取複方",
        "hero": "yi-front",
        "hero_w": "560px",
        "chips": [
            ("60粒/瓶", "#fdf3da", "#7c5606"),
            ("SGS 檢驗合格", "#fdf3da", "#7c5606"),
            ("含綜合維生素B群", "#e9eefb", "#22397c"),
        ],
        "usp_art": "yi-pair",
        "usp_art_w": "380px",
        "usp_tag": "天麻100",
        "usp": [
            ("龍眼花+天麻 雙萃取", "每粒含龍眼花萃取物 200mg、天麻萃取物 100mg"),
            ("綜合維生素B群 75mg", "B1・B2・B6・B12、菸鹼醯胺、葉酸、生物素"),
            ("蜂王乳・魚油・黑豆複方", "蜂王乳粉 50mg、魚油粉 30mg、黑豆粉 10mg"),
            ("SGS 檢驗合格", "品質把關，每日 1 粒、本包裝 60 份"),
        ],
        "ing_title": "成分與營養標示",
        "ing_tag": "每份 1 粒 · 60 份",
        "ing": [
            ("龍眼花萃取物", "200mg", False),
            ("天麻萃取物", "100mg", False),
            ("綜合維生素B群", "75mg", False),
            ("蜂王乳粉", "50mg", False),
            ("魚油粉", "30mg", False),
            ("黑豆粉", "10mg", False),
            ("維生素E粉", "5mg", False),
        ],
        "ing_art": "yi-back",
        "ing_art_bg": "#f7f6f2",
        "note_bg": "#fdf3da",
        "note_fg": "#7c5606",
        "note_body_fg": "#6b5313",
        "note_h": "營養標示重點（每日參考值）",
        "note_p": "維生素B1 104%・B2 188%・B6 154%<br>葉酸 30 微克、生物素 3 微克",
        "company": "",
        "disclaimer": "注意事項：本品含乳糖、魚油、黑豆，對其成分過敏者請留意。請置於陰涼乾燥處，避免陽光直射。",
    },
    {
        "slug": "progifted",
        "accent": "#2f7a3e",
        "accent_deep": "#1d5228",
        "bar": "linear-gradient(90deg,#1d5228,#4e9e56,#8dc63f)",
        "wash": "radial-gradient(closest-side,#eef7ee,#ffffff)",
        "chip_bg": "#e8f4e8",
        "eyebrow": "PROGIFTED® LP-28",
        "eyebrow_r": "蘋果口味・條狀包",
        "title": "Progifted LP-28 益生菌",
        "subtitle": "15種複合益生菌 ＋ 綜合酵素・120×10⁸ cfu/2g",
        "hero": "progifted",
        "hero_w": "600px",
        "chips": [
            ("30包/盒・每包2g", "#e8f4e8", "#1d5228"),
            ("120億15種活性菌株", "#e8f4e8", "#1d5228"),
            ("蘋果口味", "#fdf1e2", "#8a5410"),
        ],
        "usp_art": "progifted",
        "usp_art_w": "360px",
        "usp_tag": "LP-28®",
        "usp": [
            ("第4代專利三層包埋", "三層包埋技術，通過耐胃酸、耐膽鹽與活力穩定試驗"),
            ("120億・15種共生型菌株", "含 LP-28® 等 15 種三層包埋複合乳酸菌，每包 120×10⁸ cfu"),
            ("多國專利葡聚多醣", "獨家添加美國專利 β-葡聚多醣與菊糖"),
            ("日本天野綜合酵素", "添加日本天野製藥（Amano）3 種綜合酵素"),
        ],
        "ing_title": "成分與規格",
        "ing_tag": "每包 2g",
        "ing": [
            ("複合乳酸菌", "15種三層包埋（含LP-28®）", True),
            ("活菌數", "120×10⁸ cfu/2g", False),
            ("綜合酵素", "日本天野（Amano）3種", True),
            ("專利多醣", "β-葡聚多醣・菊糖", True),
            ("口味", "蘋果", True),
            ("規格", "30包/盒", True),
            ("品質試驗", "耐胃酸・耐膽鹽・活力穩定", True),
        ],
        "ing_art": "progifted",
        "ing_art_bg": "#f3f7f3",
        "note_bg": "#e8f4e8",
        "note_fg": "#1d5228",
        "note_body_fg": "#2b5c35",
        "note_h": "品質試驗",
        "note_p": "通過耐胃酸實驗・通過耐膽鹽實驗<br>活力穩定試驗合格",
        "company": "華貿行實業股份有限公司",
        "disclaimer": "注意事項：請置於陰涼乾燥處，避免陽光直射。",
    },
    {
        "slug": "chanc",
        "accent": "#b8860b",
        "accent_deep": "#7c5606",
        "bar": "linear-gradient(90deg,#b8860b,#e8b923,#c0392b)",
        "wash": "radial-gradient(closest-side,#fdf6e0,#ffffff)",
        "chip_bg": "#fdf3da",
        "eyebrow": "CHAN-C® TABLETS",
        "eyebrow_r": "草莓風味咀嚼錠",
        "title": '強喜<sup>®</sup> 錠',
        "subtitle": "CHAN-C® TABLETS · 草莓添加 β-胡蘿蔔素",
        "hero": "chanc",
        "hero_w": "520px",
        "chips": [
            ("80錠/盒", "#fdf3da", "#7c5606"),
            ("維他命 C＋B6", "#fdf3da", "#7c5606"),
            ("草莓風味", "#f9ecea", "#8c231e"),
            ("台灣製造", "#e9f3e6", "#2f6323"),
        ],
        "usp_art": "chanc",
        "usp_art_w": "330px",
        "usp_tag": "CHAN-C®",
        "usp": [
            ("維生素 C ＋ B6 複方", "維生素C（抗壞血酸）、抗壞血酸鈉搭配維生素B6"),
            ("添加 β-胡蘿蔔素", "另含泛酸鈣，營養更完整"),
            ("草莓風味咀嚼錠", "草莓香料調味，大人小孩都好接受"),
            ("國家品質標章", "台灣製造，井田國際醫藥廠生產"),
        ],
        "ing_title": "成分與規格",
        "ing_tag": "80 TAB",
        "ing": [
            ("維生素C（抗壞血酸）", "主要成分", True),
            ("抗壞血酸鈉", "主要成分", True),
            ("泛酸鈣", "主要成分", True),
            ("維生素B6", "主要成分", True),
            ("β-胡蘿蔔素", "主要成分", True),
            ("其他", "蔗糖、氧化澱粉、草莓香料等", True),
            ("規格", "80 錠/盒", True),
            ("產地", "台灣", True),
        ],
        "ing_art": "chanc",
        "ing_art_bg": "#faf6ea",
        "note_bg": "#fdf3da",
        "note_fg": "#7c5606",
        "note_body_fg": "#6b5313",
        "note_h": "製造與代理",
        "note_p": "製造：井田國際醫藥廠股份有限公司<br>總代理：天下生物科技股份有限公司",
        "company": "",
        "disclaimer": "注意事項：請置於陰涼乾燥處，避免陽光直射。",
    },
    {
        "slug": "bgroup",
        "accent": "#c0392b",
        "accent_deep": "#8c231e",
        "bar": "linear-gradient(90deg,#8c231e,#c0392b,#2f7a3e)",
        "wash": "radial-gradient(closest-side,#fdeeec,#ffffff)",
        "chip_bg": "#f9ecea",
        "eyebrow": "原料嚴選 DSM 德國廠",
        "eyebrow_r": "全新升級加強版",
        "title": "高優質維他命B群",
        "subtitle": "一天一粒・60 粒軟膠囊",
        "hero": "bgroup",
        "hero_w": "600px",
        "chips": [
            ("60粒 軟膠囊", "#f9ecea", "#8c231e"),
            ("DSM 德國廠原料", "#f9ecea", "#8c231e"),
            ("95% 薑黃", "#fdf1e2", "#8a5410"),
        ],
        "usp_art": "bgroup",
        "usp_art_w": "380px",
        "usp_tag": "B GROUP",
        "usp": [
            ("原料嚴選 DSM 德國廠", "維生素原料來自 DSM 德國廠"),
            ("完整 B 群", "B1・B2・B6・B12、葉酸、生物素一次補足"),
            ("95% 薑黃・啤酒酵母・五味子", "加強版配方，複方協同"),
            ("一天一粒，方便持續", "軟膠囊好吞食，60 粒約一個月份"),
        ],
        "ing_title": "成分與規格",
        "ing_tag": "60 粒 軟膠囊",
        "ing": [
            ("維生素 B1・B2・B6・B12", "維生素群", True),
            ("葉酸・生物素", "維生素群", True),
            ("95% 薑黃萃取", "複方", True),
            ("啤酒酵母", "複方", True),
            ("五味子", "複方", True),
            ("規格", "60 粒 軟膠囊", True),
        ],
        "ing_art": "bgroup",
        "ing_art_bg": "#faf3f2",
        "note_bg": "#f9ecea",
        "note_fg": "#8c231e",
        "note_body_fg": "#7a3b35",
        "note_h": "建議食用方式",
        "note_p": "每日 1 粒，搭配溫水食用。",
        "company": "",
        "disclaimer": "注意事項：請置於陰涼乾燥處，避免高溫與陽光直射；開封後請儘早食用。",
    },
    {
        "slug": "coralca",
        "accent": "#1f6f9e",
        "accent_deep": "#134a6a",
        "bar": "linear-gradient(90deg,#134a6a,#3d9ac9,#c0392b)",
        "wash": "radial-gradient(closest-side,#e9f3f9,#ffffff)",
        "chip_bg": "#e6f1f8",
        "eyebrow": "MAGNESIUM GLYCINATE",
        "eyebrow_r": "MADE IN CANADA",
        "title": "甘鎂佳 珊瑚鈣",
        "subtitle": "MAGNESIUM GLYCINATE CORAL CA · K2(MK-7) ＋ D3 ＋ Mg",
        "hero": "coralca",
        "hero_w": "520px",
        "chips": [
            ("60錠/盒", "#e6f1f8", "#134a6a"),
            ("甘胺酸鎂", "#e6f1f8", "#134a6a"),
            ("加拿大製造", "#f9ecea", "#8c231e"),
        ],
        "usp_art": "coralca",
        "usp_art_w": "340px",
        "usp_tag": "CORAL CA",
        "usp": [
            ("珊瑚鈣 Coral Ca", "以珊瑚鈣為鈣質來源"),
            ("甘胺酸鎂 Magnesium Glycinate", "鎂與鈣搭配補充"),
            ("維生素 K2（MK-7）＋ D3", "K2 選用 MK-7 形式，搭配維生素 D3"),
            ("加拿大製造", "Made in Canada，60 錠裝"),
        ],
        "ing_title": "成分與規格",
        "ing_tag": "60 TABLETS",
        "ing": [
            ("珊瑚鈣", "Coral Ca", True),
            ("甘胺酸鎂", "Magnesium Glycinate", True),
            ("維生素 K2", "MK-7", True),
            ("維生素 D3", "D3", True),
            ("規格", "60 錠/盒", True),
            ("產地", "加拿大", True),
            ("品牌", "中旗生技", True),
        ],
        "ing_art": "coralca",
        "ing_art_bg": "#f2f7fa",
        "note_bg": "#e6f1f8",
        "note_fg": "#134a6a",
        "note_body_fg": "#2b5771",
        "note_h": "保存與提醒",
        "note_p": "請置於陰涼乾燥處，避免孩童自行取用。<br>孕婦及慢性病患者食用前請諮詢專業人員。",
        "company": "中旗生物科技股份有限公司",
        "disclaimer": "注意事項：",
    },
    {
        "slug": "kurozu",
        "accent": "#c0102a",
        "accent_deep": "#8c0a1e",
        "bar": "linear-gradient(90deg,#8c0a1e,#c0102a,#c9a227)",
        "wash": "radial-gradient(closest-side,#fcf1f2,#ffffff)",
        "chip_bg": "#fbe9eb",
        "eyebrow": "東洋カプセル",
        "eyebrow_r": "保健機能食品",
        "title": "熟成 黑酢膠囊",
        "subtitle": "BLACK VINEGAR SOFT CAPSULE · 含天然胺基酸與有機酸",
        "hero": "kurozu",
        "hero_h": "420px",
        "chips": [
            ("每粒相當於米醋 80mL", "#fbe9eb", "#8c0a1e"),
            ("甕釀黑醋醪", "#fbe9eb", "#8c0a1e"),
            ("日本製法", "#f7f0dd", "#856a10"),
        ],
        "usp_art": "kurozu",
        "usp_art_w": "330px",
        "usp_tag": "黑酢カプセル",
        "usp_title": "產品特色與規格",
        "usp": [
            ("一粒濃縮 80mL 米醋", "高濃縮軟膠囊，免除喝醋的酸澀負擔"),
            ("甕釀黑醋醪", "採用傳統壺造（甕釀）黑醋醪原料製成"),
            ("天然胺基酸與有機酸", "熟成過程自然產生的胺基酸與有機酸含量豐富"),
        ],
        "spec_table": [
            ("品名", "熟成黑酢膠囊"),
            ("型態", "軟膠囊"),
            ("分類", "保健機能食品"),
        ],
        "screens": ["main", "usp"],
    },
    {
        "slug": "biostand",
        "accent": "#0b64b4",
        "accent_deep": "#0b4a86",
        "bar": "linear-gradient(90deg,#16336b,#0b64b4,#3fa9f5)",
        "wash": "radial-gradient(closest-side,#eff6fc,#ffffff)",
        "chip_bg": "#e7f1fb",
        "eyebrow": "SYNERGISTIC CALCIUM FORMULA",
        "eyebrow_r": "USA / GMP",
        "title": "挺液鈣 液態鈣膠囊",
        "subtitle": "BIO-STAND® CALCIUM CAPSULE · 美國原廠進口・升級版配方",
        "hero": "biostand",
        "hero_h": "430px",
        "chips": [
            ("100 粒/盒", "#e7f1fb", "#0b4a86"),
            ("兩種型態液態鈣", "#e7f1fb", "#0b4a86"),
            ("D3 Formula", "#e7f1fb", "#0b4a86"),
            ("防偽科技晶片", "#f9ecea", "#8c231e"),
        ],
        "usp_art": "biostand",
        "usp_art_w": "290px",
        "usp_tag": "BIO-STAND®",
        "usp": [
            ("兩種型態液態鈣", "液態鈣搭配磷與卵磷脂，升級版配方"),
            ("特別加入螯合鋅及甘胺酸鎂", "鈣、鎂、鋅與維生素 D3 協同補充"),
            ("適用族群廣", "中老年人、孕婦及授乳期、發育中的兒童學生"),
            ("防偽科技晶片", "請認明包裝上的防偽晶片，謹防假冒；商標專利第01143532號"),
        ],
        "ing_row_pad": "16px",
        "ing_title": "成分與規格",
        "ing_tag": "100 CAPSULES",
        "ing": [
            ("液態鈣", "兩種型態", False),
            ("維生素 D3", "D3 Formula", False),
            ("磷・卵磷脂", "複方協同", False),
            ("螯合鋅・甘胺酸鎂", "特別添加", False),
            ("規格", "100 粒/盒", True),
            ("產地", "美國（USA/GMP）", True),
        ],
        "ing_art": "biostand",
        "ing_art_bg": "#f0f6fa",
        "note_bg": "#e7f1fb",
        "note_fg": "#0b4a86",
        "note_body_fg": "#124e70",
        "note_h": "選購提醒",
        "note_p": "請認明防偽科技晶片，請勿購買無保障仿冒或包裝破損的產品。",
        "company": "",
        "disclaimer": "美國原廠進口｜商標專利第01143532號｜請置於陰涼乾燥處，避免陽光直射。",
    },
    {
        "slug": "congshen",
        "accent": "#c1361b",
        "accent_deep": "#8f2412",
        "bar": "linear-gradient(90deg,#8f2412,#c1361b,#e0a80c)",
        "wash": "radial-gradient(closest-side,#fcf1ee,#ffffff)",
        "chip_bg": "#fbeae5",
        "eyebrow": "一日一粒・營養補給",
        "eyebrow_r": "五種複方",
        "title": "聰身景麴<sup>®</sup>",
        "subtitle": "紅藻・綠藻・乳酸菌・酵母B群・綜合礦物質 五合一複方",
        "hero": "congshen",
        "hero_h": "420px",
        "chips": [
            ("90 Cap./盒", "#fbeae5", "#8f2412"),
            ("含蝦紅素", "#fbeae5", "#8f2412"),
            ("含鎂不含碘", "#f7f0dd", "#856a10"),
        ],
        "usp_art": "congshen",
        "usp_art_w": "320px",
        "usp_tag": "聰身景麴",
        "usp": [
            ("紅藻萃取・含蝦紅素", "以紅藻萃取為基底，天然含蝦紅素"),
            ("綠藻・含 β-1,3 葡聚醣", "綠藻提供 β-1,3 葡聚醣"),
            ("凍晶乳酸菌", "添加凍晶乳酸菌，日常保養好幫手"),
            ("酵母B群・綜合礦物質", "酵母來源維生素B群，綜合礦物質含鎂不含碘"),
        ],
        "ing_row_pad": "16px",
        "ing_title": "成分與規格",
        "ing_tag": "90 CAP.",
        "ing": [
            ("紅藻萃取", "含蝦紅素", False),
            ("綠藻", "含 β-1,3 葡聚醣", False),
            ("乳酸菌", "含凍晶乳酸菌", False),
            ("酵母B群", "含維生素B群", False),
            ("綜合礦物質", "含鎂不含碘", False),
            ("規格", "90 Cap./盒", True),
        ],
        "ing_art": "congshen",
        "ing_art_bg": "#fbf3f1",
        "note_bg": "#fbeae5",
        "note_fg": "#8f2412",
        "note_body_fg": "#7a2a1a",
        "note_h": "建議食用方式",
        "note_p": "一日一粒，做為日常營養補給。",
        "company": "",
        "disclaimer": "請置於陰涼乾燥處，避免陽光直射；開封後請儘早食用。",
    },
    {
        "slug": "richingsheng",
        "accent": "#16336b",
        "accent_deep": "#16336b",
        "bar": "linear-gradient(90deg,#16336b,#2f5fa8,#8a6a2e)",
        "wash": "radial-gradient(closest-side,#f1f3fa,#ffffff)",
        "chip_bg": "#e9edf7",
        "eyebrow": "賢士 · ORAL PROBIOTIC SUPPLEMENT",
        "eyebrow_r": "60 粒入",
        "title": "日清勝<sup>®</sup> 口服益生菌",
        "subtitle": "添加專利乳酸菌發酵物 SynForU® · SYNTEK®",
        "hero": "richingsheng",
        "hero_h": "340px",
        "chips": [
            ("60 粒/盒", "#e9edf7", "#16336b"),
            ("調整體質", "#e9edf7", "#16336b"),
            ("幫助消化", "#e9edf7", "#16336b"),
            ("使排便順暢", "#f5f0e4", "#7d6423"),
        ],
        "usp_art": "richingsheng",
        "usp_art_w": "340px",
        "usp_tag": "REMAIN PROBIOTICS",
        "usp": [
            ("專利乳酸菌發酵物", "添加 SynForU® 專利乳酸菌發酵物"),
            ("SYNTEK® 技術", "晨望生技 Horizon Biotech 監製"),
            ("調整體質・幫助消化", "日常保養，由內而外打底"),
            ("使排便順暢", "60 粒盒裝，方便每日食用"),
        ],
        "ing_row_pad": "15px",
        "ing_title": "成分與規格",
        "ing_tag": "60 粒入",
        "ing": [
            ("專利乳酸菌發酵物", "SynForU®", False),
            ("製程技術", "SYNTEK®", False),
            ("品牌", "賢士・晨望生技", False),
            ("規格", "60 粒/盒", True),
        ],
        "ing_art": "richingsheng",
        "ing_art_bg": "#f1f3f6",
        "note_bg": "#e9edf7",
        "note_fg": "#16336b",
        "note_body_fg": "#22406f",
        "note_h": "產品訴求",
        "note_p": "調整體質・幫助消化・使排便順暢",
        "company": "",
        "disclaimer": "晨望生技股份有限公司｜請置於陰涼乾燥處，避免陽光直射。",
    },
    {
        "slug": "guguanjian",
        "accent": "#0f6b3a",
        "accent_deep": "#0b4d2a",
        "bar": "linear-gradient(90deg,#0b4d2a,#0f6b3a,#dccf1e)",
        "wash": "radial-gradient(closest-side,#f0f7f1,#ffffff)",
        "chip_bg": "#e8f3ea",
        "eyebrow": "UC II® 非變性二型膠原蛋白",
        "eyebrow_r": "健康輔助食品",
        "title": "固關鍵<sup>®</sup> UC II 膠囊",
        "subtitle": "非變性二型膠原蛋白 ＋ 北海道鱈魚鼻軟骨・每日足量 40mg",
        "hero": "guguanjian",
        "hero_h": "425px",
        "chips": [
            ("60粒/膠囊", "#e8f3ea", "#0b4d2a"),
            ("95% 玻尿酸", "#e8f3ea", "#0b4d2a"),
            ("專利 MSM", "#e8f3ea", "#0b4d2a"),
            ("葡萄糖胺・乳油木果", "#f7f4dc", "#7a7310"),
        ],
        "usp_art": "guguanjian",
        "usp_art_w": "300px",
        "usp_tag": "UC II®",
        "usp": [
            ("每日足量 40mg/天", "添加每日所需足量非變性二型膠原蛋白"),
            ("北海道鱈魚鼻軟骨", "選用北海道鱈魚鼻軟骨為原料來源"),
            ("95% 玻尿酸 ＋ 專利 MSM", "高比例玻尿酸搭配專利 MSM"),
            ("葡萄糖胺・乳油木果", "複方協同，行動保養一次到位"),
        ],
        "ing_row_pad": "16px",
        "ing_title": "成分與規格",
        "ing_tag": "60 粒/膠囊",
        "ing": [
            ("非變性二型膠原蛋白", "40mg/天", False),
            ("北海道鱈魚鼻軟骨", "原料來源", False),
            ("玻尿酸", "95%", False),
            ("MSM", "專利原料", False),
            ("葡萄糖胺・乳油木果", "複方添加", False),
            ("規格", "60 粒/盒", True),
        ],
        "ing_art": "guguanjian",
        "ing_art_bg": "#f1f6f3",
        "note_bg": "#e8f3ea",
        "note_fg": "#0b4d2a",
        "note_body_fg": "#1a5c34",
        "note_h": "產品定位",
        "note_p": "健康輔助食品，適合日常行動保養。",
        "company": "",
        "disclaimer": "本產品含魚類成分，對其過敏者請留意。請置於陰涼乾燥處，避免陽光直射。",
    },
    {
        "slug": "jinguguanjian",
        "accent": "#a9801a",
        "accent_deep": "#7d5c10",
        "bar": "linear-gradient(90deg,#8a6412,#c8a13a,#c2185b)",
        "wash": "radial-gradient(closest-side,#faf6ea,#ffffff)",
        "chip_bg": "#f8f1de",
        "eyebrow": "TERYLEAF · 中美製藥集團",
        "eyebrow_r": "緩釋錠 60 錠入",
        "title": "金固關健 緩釋錠",
        "subtitle": "UNDENATURED COLLAGEN TYPE II · 慢溶長效，持續作用",
        "hero": "jinguguanjian",
        "hero_h": "420px",
        "chips": [
            ("60 錠入", "#f8f1de", "#7d5c10"),
            ("42mg 非變性II型膠原蛋白", "#f8f1de", "#7d5c10"),
            ("340mg MSM", "#fbe9ef", "#a5104a"),
            ("500mg 乳木果油", "#fbe9ef", "#a5104a"),
        ],
        "usp_art": "jinguguanjian",
        "usp_art_w": "330px",
        "usp_tag": "TERYLEAF",
        "usp": [
            ("緩釋技術・慢溶長效", "緩釋錠型設計，慢慢溶解、長時間作用"),
            ("42mg 非變性II型膠原蛋白", "Undenatured Collagen Type II 足量添加"),
            ("340mg MSM ＋ 500mg 乳木果油", "三重複方，行動與修護一併照顧"),
            ("鋅 ＋ 維生素 D", "支援肌肉與生理機能維持，補足日常活力"),
        ],
        "ing_row_pad": "16px",
        "ing_title": "成分與規格",
        "ing_tag": "60 錠入",
        "ing": [
            ("非變性II型膠原蛋白", "42mg", False),
            ("MSM", "340mg", False),
            ("乳木果油", "500mg", False),
            ("鋅", "活力支援", False),
            ("維生素 D", "體格維持", False),
            ("規格", "60 錠/盒（緩釋錠）", True),
        ],
        "ing_art": "jinguguanjian",
        "ing_art_bg": "#faf7f1",
        "note_bg": "#f8f1de",
        "note_fg": "#7d5c10",
        "note_body_fg": "#6d5312",
        "note_h": "品牌授權",
        "note_p": "日糧（台灣）官方授權・品牌授權國際總經銷 中美製藥集團 Chung-Mei Pharm. Group",
        "company": "",
        "disclaimer": "營養的供給・60 錠入｜請置於陰涼乾燥處，避免陽光直射。",
    },
    {
        "slug": "youweining",
        "accent": "#3f8f27",
        "accent_deep": "#2c6b1c",
        "bar": "linear-gradient(90deg,#2c6b1c,#5aa832,#e0a80c)",
        "wash": "radial-gradient(closest-side,#f1f8ed,#ffffff)",
        "chip_bg": "#eaf4e4",
        "eyebrow": "ROYAL AUSTRALIA",
        "eyebrow_r": "純素可食",
        "title": "佑衛寧 高麗菜濃縮複方膠囊",
        "subtitle": "GROW 專利 S-CABBAGE® 天然全食物型態高麗菜濃縮精華",
        "hero": "youweining",
        "hero_h": "425px",
        "chips": [
            ("30 Capsules", "#eaf4e4", "#2c6b1c"),
            ("低溫超音波萃取", "#eaf4e4", "#2c6b1c"),
            ("冷凍乾燥製程", "#eaf4e4", "#2c6b1c"),
            ("純素可食", "#f7f0dd", "#856a10"),
        ],
        "usp_art": "youweining",
        "usp_art_w": "300px",
        "usp_tag": "S-CABBAGE®",
        "usp": [
            ("Grow 專利 S-Cabbage", "天然全食物型態的高麗菜濃縮精華"),
            ("獨家專利低溫超音波", "多項獨家專利低溫超音波技術萃取"),
            ("冷凍乾燥保留活性", "冷凍乾燥製成，有效保存活性物質"),
            ("多種大自然成分", "來自多種天然食材，品質優異無負擔，純素可食"),
        ],
        "ing_row_pad": "16px",
        "ing_title": "成分與規格",
        "ing_tag": "30 CAPSULES",
        "ing": [
            ("高麗菜濃縮精華", "S-Cabbage®", False),
            ("萃取技術", "低溫超音波", False),
            ("乾燥製程", "冷凍乾燥", False),
            ("素食別", "純素可食", True),
            ("規格", "30 粒/盒", True),
        ],
        "ing_art": "youweining",
        "ing_art_bg": "#f3f8f2",
        "note_bg": "#eaf4e4",
        "note_fg": "#2c6b1c",
        "note_body_fg": "#33652a",
        "note_h": "品牌",
        "note_p": "Royal Australia",
        "company": "",
        "disclaimer": "請置於陰涼乾燥處，避免陽光直射；孕婦及慢性病患者食用前請諮詢專業人員。",
    },
    {
        "slug": "glutamine",
        "accent": "#1565c0",
        "accent_deep": "#0d2b5e",
        "bar": "linear-gradient(90deg,#0d2b5e,#1565c0,#5ab4e8)",
        "wash": "radial-gradient(closest-side,#f0f6fc,#ffffff)",
        "chip_bg": "#e8f1fb",
        "eyebrow": "NUTRITIONAL SUPPORT",
        "eyebrow_r": "5g × 30 包",
        "title": "賜利康<sup>®</sup> 左旋麩醯胺酸",
        "subtitle": "L-GLUTAMINE · 100% NUTRITIONAL SUPPORT",
        "hero": "glutamine",
        "hero_h": "405px",
        "chips": [
            ("5g/包・30 包", "#e8f1fb", "#0d2b5e"),
            ("幫助維持消化道機能", "#e8f1fb", "#0d2b5e"),
            ("幫助維持保護力", "#e8f1fb", "#0d2b5e"),
            ("運動後恢復", "#e6f7f5", "#136b60"),
        ],
        "usp_art": "glutamine",
        "usp_art_w": "340px",
        "usp_tag": "L-GLUTAMINE",
        "usp": [
            ("幫助維持消化道機能", "Supports Digestive Health"),
            ("幫助維持保護力", "Supports Immune Function"),
            ("幫助運動後恢復", "Supports Muscle Recovery"),
            ("單包 5g 隨身包", "30 包/盒，免量取、沖泡方便"),
        ],
        "ing_row_pad": "16px",
        "ing_title": "成分與規格",
        "ing_tag": "5g / 30 PACKETS",
        "ing": [
            ("左旋麩醯胺酸", "L-Glutamine", False),
            ("每包淨重", "5 公克", True),
            ("內容量", "30 包/盒", True),
            ("分類", "膳食補充食品", True),
        ],
        # 設計稿在成分表下面多一排訴求 chip —— 全 21 項只有這張有
        "ing_chips": ["消化道機能", "保護力", "運動恢復", "健康維持"],
        "ing_art": "glutamine",
        "ing_art_bg": "#f1f6fb",
        "note_bg": "#e8f1fb",
        "note_fg": "#0d2b5e",
        "note_body_fg": "#164a86",
        "note_h": "建議食用方式",
        "note_p": "每日 1 包，以溫水或飲品沖泡後食用。",
        "company": "",
        "disclaimer": "Dietary Supplement・Health Maintenance｜請置於陰涼乾燥處，開封後請儘早食用。",
    },
    {
        "slug": "mg",
        "accent": "#1e6b3a",
        "accent_deep": "#1e6b3a",
        "bar": "linear-gradient(90deg,#1e6b3a,#4a9e2f,#c2185b)",
        "wash": "radial-gradient(closest-side,#f0f7f1,#ffffff)",
        "chip_bg": "#e8f2ea",
        "eyebrow": "優全生技 · 生物科技產品",
        "eyebrow_r": "全素食品",
        "title": "新優力 超級鎂",
        "subtitle": "Mg SOD＋3 · 配方專利新型號 第 M507762 號",
        "hero": "mg",
        "hero_h": "428px",
        "chips": [
            ("20 capsule", "#e8f2ea", "#1e6b3a"),
            ("配方專利", "#e8f2ea", "#1e6b3a"),
            ("打鎂鎂力・健康新生活", "#fbe9ef", "#a5104a"),
            ("全素食品", "#e8f2ea", "#1e6b3a"),
        ],
        "usp_art": "mg",
        "usp_art_w": "290px",
        "usp_tag": "Mg SOD＋3",
        "usp_title": "產品特色與規格",
        "usp": [
            ("Mg ＋ SOD 複方", "鎂搭配 SOD＋3 配方設計"),
            ("配方專利新型號", "第 M507762 號專利配方"),
            ("全素可食", "全素食品，素食者可安心食用"),
        ],
        "spec_table": [
            ("品名", "新優力超級鎂 Mg SOD＋3"),
            ("內容量", "20 capsule"),
            ("專利", "第 M507762 號"),
            ("品牌", "優全生技 YU CHUAN"),
        ],
        "screens": ["main", "usp"],
    },
    {
        # 這張的底圖是示意盒（不是護欣胺的實際包裝），文字不能照抄盒面 ——
        # 盒面的「120 vegetarian capsules」與 Healthy Cycle 都是示意盒自己的
        # 字。文案一律取自 lib/data.ts 的品項資料，規格照目錄標「待確認」。
        "slug": "arginine",
        "accent": "#15357e",
        "accent_deep": "#15357e",
        "bar": "linear-gradient(90deg,#15357e,#3f6fd0,#d32f2f)",
        "wash": "radial-gradient(closest-side,#f0f3fa,#ffffff)",
        "chip_bg": "#e8ecf8",
        "eyebrow": "精萃載體科技",
        "eyebrow_r": "微粒膠囊",
        "title": "護欣胺微粒膠囊",
        "subtitle": "L-ARGININE · AMINO ACIDS · PLANT EXTRACTS & VITAMINS",
        "hero": "arginine",
        "hero_h": "425px",
        "chips": [
            ("L-精胺酸配方", "#e8ecf8", "#15357e"),
            ("微粒膠囊", "#e8ecf8", "#15357e"),
            ("規格待確認", "#f1f1ec", "#5a616b"),
        ],
        "usp_art": "arginine",
        "usp_art_w": "290px",
        "usp_tag": "L-ARGININE",
        "usp_title": "產品特色與規格",
        "usp": [
            ("L-精胺酸為主的配方", "L-精胺酸為體內合成一氧化氮的前驅胺基酸"),
            ("胺基酸、植物萃取物與維生素", "維生素C、松樹皮萃取物、L-麩醯胺酸、綠茶萃取物、丹參萃取物、維生素E、葉酸"),
            ("包裝規格待確認", "內容量與規格以合作藥局實際供應的包裝為準"),
        ],
        "spec_table": [
            ("品名", "護欣胺微粒膠囊"),
            ("劑型", "微粒膠囊"),
            ("廠商", "精萃載體科技股份有限公司"),
            ("產地", "台灣"),
        ],
        "screens": ["main", "usp"],
    },
    {
        "slug": "guerhgan",
        "accent": "#1b7a3d",
        "accent_deep": "#125c2d",
        "bar": "linear-gradient(90deg,#125c2d,#1b7a3d,#e0b400)",
        "wash": "radial-gradient(closest-side,#f0f7f3,#ffffff)",
        "chip_bg": "#e8f3ec",
        "eyebrow": "中美醫藥 SYNTHOMED",
        "eyebrow_r": "100 粒入",
        "title": "顧爾肝<sup>®</sup> 護肝片",
        "subtitle": "CUNGAN CAPSULES 150mg (SILYMARIN) · 草本精華素",
        "hero": "guerhgan",
        "hero_h": "390px",
        "chips": [
            ("100 粒/盒", "#e8f3ec", "#125c2d"),
            ("Silymarin 150mg", "#e8f3ec", "#125c2d"),
            ("全新強效配方", "#f8f2dc", "#7d6510"),
            ("HKP-08936", "#e8f3ec", "#125c2d"),
        ],
        "usp_art": "guerhgan",
        "usp_art_w": "340px",
        "usp_tag": "SILYMARIN",
        "usp": [
            ("Silymarin 護肝精華素", "每粒含 150mg Silymarin（草本精華素）"),
            ("全新強效配方", "配方升級，草本精華濃度更集中"),
            ("香港中成藥註冊", "註冊編號 HKP-08936"),
            ("100 粒大包裝", "中美醫藥集團 Synthomed 出品"),
        ],
        "ing_row_pad": "16px",
        "ing_title": "成分與規格",
        "ing_tag": "100 粒入",
        "ing": [
            ("Silymarin（草本精華素）", "150mg", False),
            ("產品英文名", "Cungan Capsules", False),
            ("註冊編號", "HKP-08936", False),
            ("劑型", "膠囊", True),
            ("規格", "100 粒/盒", True),
        ],
        "ing_art": "guerhgan",
        "ing_art_bg": "#f1f7f3",
        "note_bg": "#e8f3ec",
        "note_fg": "#125c2d",
        "note_body_fg": "#1a5c34",
        "note_h": "製造商",
        "note_p": "中美醫藥 Synthomed",
        "company": "",
        "disclaimer": "香港中成藥註冊編號：HKP-08936｜請依標示服用，並置於陰涼乾燥處。",
    },
    {
        "slug": "sbenlin",
        "accent": "#6f8c0e",
        "accent_deep": "#5d7510",
        "bar": "linear-gradient(90deg,#0f7a63,#9cc11a,#c9a227)",
        "wash": "radial-gradient(closest-side,#f7f9ea,#ffffff)",
        "chip_bg": "#f2f6df",
        "eyebrow": "11 種草本生藥萃取菁華",
        "eyebrow_r": "High Potency",
        "title": "益聖靈-P 軟膠囊",
        "subtitle": "SBENLIN-P® SOFT CAPSULES · 1000mg",
        "hero": "sbenlin",
        "hero_h": "425px",
        "chips": [
            ("60 粒軟膠囊", "#f2f6df", "#5d7510"),
            ("每粒 1000mg", "#f2f6df", "#5d7510"),
            ("11 種草本生藥", "#e2f2ee", "#0f7a63"),
        ],
        "usp_art": "sbenlin",
        "usp_art_w": "300px",
        "usp_tag": "SBENLIN-P®",
        "usp_title": "產品特色與規格",
        "usp": [
            ("11 種草本生藥萃取菁華", "多種草本生藥複方萃取，菁華濃縮"),
            ("高單位 1000mg", "每粒 1000mg，High Potency 高效配方"),
            ("軟膠囊好吞食", "軟膠囊劑型，吸收與服用皆便利"),
        ],
        "spec_table": [
            ("品名", "益聖靈-P 軟膠囊"),
            ("每粒含量", "1000mg"),
            ("內容量", "60 粒軟膠囊"),
        ],
        "screens": ["main", "usp"],
    },
    {
        "slug": "maca",
        "accent": "#8a6a22",
        "accent_deep": "#6f5417",
        "bar": "linear-gradient(90deg,#1a1a1a,#8a6a22,#cbab6a)",
        "wash": "radial-gradient(closest-side,#f8f5ec,#ffffff)",
        "chip_bg": "#f4efe2",
        "eyebrow": "OU YEH PHARMACEUTICAL",
        "eyebrow_r": "原產地：美國",
        "title": "勁勇 軟膠囊",
        "subtitle": "MEN'S MACA · 瑪卡 ＋ 左旋精胺酸 ＋ 鹿茸複方",
        "hero": "maca",
        "hero_h": "370px",
        "chips": [
            ("軟膠囊", "#f4efe2", "#6f5417"),
            ("美國原產", "#f4efe2", "#6f5417"),
            ("11 種複方成分", "#ecedef", "#333a43"),
            ("品質保證", "#fbeaea", "#a12222"),
        ],
        "usp_art": "maca",
        "usp_art_w": "340px",
        "usp_tag": "MEN'S MACA",
        "usp": [
            ("瑪卡根萃取為核心", "Maca Root Extract 搭配左旋精胺酸"),
            ("鹿茸・鹿肉精華", "Pilose Antler、Deer Meat 傳統滋補素材"),
            ("草本與鋅、B 群協同", "銀杏、葫蘆巴、肉蓯蓉、葡萄糖酸鋅、B1/B2/B6/B12"),
            ("美國原產・品質保證", "原產地美國，歐業製藥出品"),
        ],
        "ing_row_pad": "14px",
        "ing_title": "成分與規格",
        "ing_tag": "軟膠囊",
        "ing": [
            ("瑪卡根萃取", "Maca Root Extract", False),
            ("左旋精胺酸", "L-Arginine", False),
            ("鹿肉・鹿茸", "Deer Meat・Pilose Antler", False),
            ("達米阿那葉萃取", "Damiana Leaf", False),
            ("銀杏果粉・肉蓯蓉萃取", "Ginkgo・Cistanche", False),
            ("葫蘆巴・南瓜籽油", "Trigonella・Pumpkin Seed Oil", False),
            ("葡萄糖酸鋅・維生素B群", "Zinc・B1 B2 B6 B12", False),
        ],
        "ing_art": "maca",
        "ing_art_bg": "#f8f6f2",
        "note_bg": "#f4efe2",
        "note_fg": "#6f5417",
        "note_body_fg": "#6b5622",
        "note_h": "產地與品牌",
        "note_p": "原產地：美國｜歐業製藥 OUYeh",
        "company": "",
        "disclaimer": "本產品含鹿茸等動物性成分，孕婦、哺乳期婦女及慢性疾病者食用前請諮詢專業人員。",
    },
]
