"""電商產品圖的文案與版位資料。

內容照 Claude Design 專案「電商產品圖製作」的 電商產品圖.dc.html，數字一律回頭
對過實體包裝照與 `lib/data.ts`。與設計稿不同之處只有一處：設計稿把 DEFENSE 的
`company` 寫成「國鼎生物科技有限公司」，實際是「圓鼎」（包裝、data.ts 與店家
三方一致，2026-08-18 由店家確認）。

`asset` 為 None 代表素材還沒到位；版型會畫出明顯的缺件標記，不會靜默輸出空白圖。
"""

from __future__ import annotations

# 素材檔名 → 是否已備妥。缺的三張需要店家補原始照片。
MISSING_NOTE = {
    "defense-back": "缺 Defense 背面標示照",
    "yi-back": "缺 憶元素 營養標示照",
    "aob": "缺 AOB 商品照",
}

PRODUCTS = [
    {
        "slug": "defense",
        "accent": "#4d7c2a",
        "accent_deep": "#2f5417",
        "bar": "linear-gradient(90deg,#3d6420,#6ea23c,#e2953a)",
        "wash": "radial-gradient(closest-side,#f2f7ea,#ffffff)",
        "chip_bg": "#eef4e4",
        "eyebrow": "PUREGPS® 系列",
        "eyebrow_r": "植物膠囊・全素",
        "title": '強抗力優<sup>®</sup> 450⁺ 膠囊',
        "subtitle": "DEFENSE 450⁺ · β-1,3/1,6 GLUCO POLYSACCHARIDE",
        "hero": "defense-front",
        "hero_w": "600px",
        "chips": [
            ("60粒/盒・每粒450mg", "#eef4e4", "#2f5417"),
            ("Wellmune WGP® 原料", "#eef4e4", "#2f5417"),
            ("FDA APPROVED", "#fdf1e2", "#8a5410"),
        ],
        "usp_art": "defense-front",
        "usp_art_w": "360px",
        "usp_tag": "DEFENSE 450⁺",
        "usp": [
            ("高純度多醣體", "專利技術純化酵母，β-1,3/1,6 長鏈酵母葡聚多醣體純度高達 75% 以上"),
            ("國際原料授權", "採用 Wellmune WGP®，屬 Kerry 公司原料授權使用"),
            ("國際獲獎配方", "榮獲 2007 年 IFT 美國食品科學學會「創新研究獎」"),
            ("每天 1 顆，輕鬆保養", "每顆膠囊含 400mg β-1,3/1,6 酵母葡聚多醣體，天天食用防護周到"),
        ],
        "ing_row_pad": "17px",
        "ing_title": "成分與規格",
        "ing_tag": "每粒 450mg",
        "ing": [
            ("非水溶性葡聚多醣體", "250mg", False),
            ("水溶性葡聚多醣體", "150mg", False),
            ("穀胱甘肽", "50mg", False),
            ("植物膠囊基底", "纖維素・鹿角菜膠・氯化鉀", True),
            ("規格", "每盒 60 粒", True),
            ("產地", "台灣", True),
        ],
        "ing_art": None,          # defense-back 尚缺
        "ing_art_key": "defense-back",
        "ing_art_bg": "#f6f7f4",
        "note_bg": "#eef4e4",
        "note_fg": "#2f5417",
        "note_body_fg": "#3d5227",
        "note_h": "食用方法",
        "note_p": "每日 1~2 粒，餐後食用。請保存於陰涼乾燥處，避免熱及陽光直射。",
        "company": "圓鼎生物科技有限公司",
        "disclaimer": "注意事項：孕婦及授乳中婦女請遵照醫師指示食用；對穀胱甘肽過敏者、孕婦、哺乳婦女及嬰幼兒應避免食用。",
    },
    {
        "slug": "aob",
        "accent": "#3a8a7a",
        "accent_deep": "#23695c",
        "bar": "linear-gradient(90deg,#23695c,#6cc4b2,#b08d4f)",
        "wash": "radial-gradient(closest-side,#e9f6f2,#ffffff)",
        "chip_bg": "#e7f5f1",
        "eyebrow": "NEW · VITALITY BEAUTY",
        "eyebrow_r": "條狀隨身包",
        "title": "New AOB Vitality Beauty",
        "subtitle": "健全體調・美容增進",
        "hero": None,             # AOB 商品照尚缺
        "hero_key": "aob",
        "hero_w": "560px",
        "chips": [
            ("45包/盒", "#e7f5f1", "#23695c"),
            ("鋁袋條狀隨身包", "#e7f5f1", "#23695c"),
            ("NEW 配方", "#f5efe2", "#7c6230"),
        ],
        "usp_art": None,
        "usp_art_key": "aob",
        "usp_art_w": "400px",
        "usp_tag": "AOB",
        "usp_title": "產品特色與規格",
        "usp": [
            ("健全體調", "以日常保養為本，做好每天的健康打底"),
            ("美容增進", "內外兼顧，同時照顧美容保養需求"),
            ("45 包條狀隨身包", "單包分裝、免量取，通勤外出輕鬆帶著走"),
        ],
        "spec_table": [
            ("品名", "New AOB Vitality Beauty"),
            ("內容量", "45 包/盒"),
            ("包裝形式", "鋁袋條狀隨身包"),
        ],
        "screens": ["main", "usp"],
    },
    {
        "slug": "elgucare",
        "accent": "#24418f",
        "accent_deep": "#16295c",
        "bar": "linear-gradient(90deg,#16295c,#24418f,#bd2f28)",
        "wash": "radial-gradient(closest-side,#eef1f9,#ffffff)",
        "chip_bg": "#eaeff9",
        "eyebrow": "LHBcare® 綠杏",
        "eyebrow_r": "全素可食",
        "title": '綠杏 益固康<sup>®</sup> 膠囊',
        "subtitle": "ELGUCARE® · NEW TECHNIQUES OF NATURAL HERBAL FORMULAS",
        "hero": "elgucare-hero",
        "hero_h": "520px",
        "chips": [
            ("瓶裝 360粒", "#eaeff9", "#16295c"),
            ("盒裝 72粒・每粒600mg", "#eaeff9", "#16295c"),
            ("全素可食", "#e9f3e6", "#2f6323"),
            ("產地台灣", "#f9ecea", "#8c231e"),
        ],
        "usp_art": "elgucare-bottle",
        "usp_art_w": "340px",
        "usp_tag": "ELGUCARE®",
        "usp": [
            ("中醫藥專家研製", "集多年經驗，依人體生理機能需要特別研製的保健配方"),
            ("八種草本萃取複方", "黃耆・紅棗・丹參・雞屎藤・伸筋草・玉竹・紅景天・甘草"),
            ("生活挺立、能量豐沛", "日常保健，可讓生活挺立、豐沛人體能量"),
            ("全素可食", "素食者可安心食用，兩種容量規格自由選擇"),
        ],
        "ing_title": "成分與建議用量",
        "ing_tag": "每粒 600mg",
        "ing": [
            ("黃耆萃取", "210mg", False),
            ("紅棗萃取", "100mg", False),
            ("丹參萃取", "45mg", False),
            ("雞屎藤萃取", "35mg", False),
            ("伸筋草萃取", "35mg", False),
            ("玉竹萃取", "35mg", False),
            ("紅景天萃取", "20mg", False),
            ("甘草萃取", "20mg", False),
        ],
        "ing_art": "elgucare-box",
        "ing_art_bg": "#f5f6f8",
        "note_bg": "#eaeff9",
        "note_fg": "#16295c",
        "note_body_fg": "#2c3a5e",
        "note_h": "建議用量",
        "note_p": "保健：每日 2 次，每次 1~2 粒<br>加強：每日 2 次，每次 2~3 粒<br>飯前空腹食用最佳，多食無益",
        "company": "綠杏生物科技有限公司 總經銷",
        "disclaimer": "注意事項：避免孩童自行取用，請置於陰涼處、避免陽光直射。產地：台灣｜",
    },
    {
        "slug": "yiyuansu",
        "accent": "#b87c08",
        "accent_deep": "#7c5606",
        "bar": "linear-gradient(90deg,#b87c08,#eab52c,#2c4a9e)",
        "wash": "radial-gradient(closest-side,#fdf4dc,#ffffff)",
        "chip_bg": "#fdf3da",
        "eyebrow": "天麻100膠囊 · 食品",
        "eyebrow_r": "SGS 檢驗合格",
        "title": "憶元素 天麻100膠囊",
        "subtitle": "TIANMA 100 CAPSULES · 龍眼花+天麻雙萃取複方",
        "hero": "yi-front",
        "hero_w": "560px",
        "chips": [
            ("60粒/瓶", "#fdf3da", "#7c5606"),
            ("SGS 檢驗合格", "#fdf3da", "#7c5606"),
            ("含綜合維生素B群", "#e9eefb", "#22397c"),
        ],
        "usp_art": "yi-pair",
        "usp_art_w": "380px",
        "usp_tag": "天麻100",
        "usp": [
            ("龍眼花+天麻 雙萃取", "每粒含龍眼花萃取物 200mg、天麻萃取物 100mg"),
            ("綜合維生素B群 75mg", "B1・B2・B6・B12、菸鹼醯胺、葉酸、生物素"),
            ("蜂王乳・魚油・黑豆複方", "蜂王乳粉 50mg、魚油粉 30mg、黑豆粉 10mg"),
            ("SGS 檢驗合格", "品質把關，每日 1 粒、本包裝 60 份"),
        ],
        "ing_title": "成分與營養標示",
        "ing_tag": "每份 1 粒 · 60 份",
        "ing": [
            ("龍眼花萃取物", "200mg", False),
            ("天麻萃取物", "100mg", False),
            ("綜合維生素B群", "75mg", False),
            ("蜂王乳粉", "50mg", False),
            ("魚油粉", "30mg", False),
            ("黑豆粉", "10mg", False),
            ("維生素E粉", "5mg", False),
        ],
        "ing_art": None,          # yi-back 尚缺
        "ing_art_key": "yi-back",
        "ing_art_bg": "#f7f6f2",
        "note_bg": "#fdf3da",
        "note_fg": "#7c5606",
        "note_body_fg": "#6b5313",
        "note_h": "營養標示重點（每日參考值）",
        "note_p": "維生素B1 104%・B2 188%・B6 154%<br>葉酸 30 微克、生物素 3 微克",
        "company": "",
        "disclaimer": "注意事項：本品含乳糖、魚油、黑豆，對其成分過敏者請留意。請置於陰涼乾燥處，避免陽光直射。",
    },
    {
        "slug": "progifted",
        "accent": "#2f7a3e",
        "accent_deep": "#1d5228",
        "bar": "linear-gradient(90deg,#1d5228,#4e9e56,#8dc63f)",
        "wash": "radial-gradient(closest-side,#eef7ee,#ffffff)",
        "chip_bg": "#e8f4e8",
        "eyebrow": "PROGIFTED® LP-28",
        "eyebrow_r": "蘋果口味・條狀包",
        "title": "Progifted LP-28 益生菌",
        "subtitle": "15種複合益生菌 ＋ 綜合酵素・120×10⁸ cfu/2g",
        "hero": "progifted",
        "hero_w": "600px",
        "chips": [
            ("30包/盒・每包2g", "#e8f4e8", "#1d5228"),
            ("120億15種活性菌株", "#e8f4e8", "#1d5228"),
            ("蘋果口味", "#fdf1e2", "#8a5410"),
        ],
        "usp_art": "progifted",
        "usp_art_w": "360px",
        "usp_tag": "LP-28®",
        "usp": [
            ("第4代專利三層包埋", "三層包埋技術，通過耐胃酸、耐膽鹽與活力穩定試驗"),
            ("120億・15種共生型菌株", "含 LP-28® 等 15 種三層包埋複合乳酸菌，每包 120×10⁸ cfu"),
            ("多國專利葡聚多醣", "獨家添加美國專利 β-葡聚多醣與菊糖"),
            ("日本天野綜合酵素", "添加日本天野製藥（Amano）3 種綜合酵素"),
        ],
        "ing_title": "成分與規格",
        "ing_tag": "每包 2g",
        "ing": [
            ("複合乳酸菌", "15種三層包埋（含LP-28®）", True),
            ("活菌數", "120×10⁸ cfu/2g", False),
            ("綜合酵素", "日本天野（Amano）3種", True),
            ("專利多醣", "β-葡聚多醣・菊糖", True),
            ("口味", "蘋果", True),
            ("規格", "30包/盒", True),
            ("品質試驗", "耐胃酸・耐膽鹽・活力穩定", True),
        ],
        "ing_art": "progifted",
        "ing_art_bg": "#f3f7f3",
        "note_bg": "#e8f4e8",
        "note_fg": "#1d5228",
        "note_body_fg": "#2b5c35",
        "note_h": "品質試驗",
        "note_p": "通過耐胃酸實驗・通過耐膽鹽實驗<br>活力穩定試驗合格",
        "company": "華貿行實業股份有限公司",
        "disclaimer": "注意事項：請置於陰涼乾燥處，避免陽光直射。",
    },
    {
        "slug": "chanc",
        "accent": "#b8860b",
        "accent_deep": "#7c5606",
        "bar": "linear-gradient(90deg,#b8860b,#e8b923,#c0392b)",
        "wash": "radial-gradient(closest-side,#fdf6e0,#ffffff)",
        "chip_bg": "#fdf3da",
        "eyebrow": "CHAN-C® TABLETS",
        "eyebrow_r": "草莓風味咀嚼錠",
        "title": '強喜<sup>®</sup> 錠',
        "subtitle": "CHAN-C® TABLETS · 草莓添加 β-胡蘿蔔素",
        "hero": "chanc",
        "hero_w": "520px",
        "chips": [
            ("80錠/盒", "#fdf3da", "#7c5606"),
            ("維他命 C＋B6", "#fdf3da", "#7c5606"),
            ("草莓風味", "#f9ecea", "#8c231e"),
            ("台灣製造", "#e9f3e6", "#2f6323"),
        ],
        "usp_art": "chanc",
        "usp_art_w": "330px",
        "usp_tag": "CHAN-C®",
        "usp": [
            ("維生素 C ＋ B6 複方", "維生素C（抗壞血酸）、抗壞血酸鈉搭配維生素B6"),
            ("添加 β-胡蘿蔔素", "另含泛酸鈣，營養更完整"),
            ("草莓風味咀嚼錠", "草莓香料調味，大人小孩都好接受"),
            ("國家品質標章", "台灣製造，井田國際醫藥廠生產"),
        ],
        "ing_title": "成分與規格",
        "ing_tag": "80 TAB",
        "ing": [
            ("維生素C（抗壞血酸）", "主要成分", True),
            ("抗壞血酸鈉", "主要成分", True),
            ("泛酸鈣", "主要成分", True),
            ("維生素B6", "主要成分", True),
            ("β-胡蘿蔔素", "主要成分", True),
            ("其他", "蔗糖、氧化澱粉、草莓香料等", True),
            ("規格", "80 錠/盒", True),
            ("產地", "台灣", True),
        ],
        "ing_art": "chanc",
        "ing_art_bg": "#faf6ea",
        "note_bg": "#fdf3da",
        "note_fg": "#7c5606",
        "note_body_fg": "#6b5313",
        "note_h": "製造與代理",
        "note_p": "製造：井田國際醫藥廠股份有限公司<br>總代理：天下生物科技股份有限公司",
        "company": "",
        "disclaimer": "注意事項：請置於陰涼乾燥處，避免陽光直射。",
    },
    {
        "slug": "bgroup",
        "accent": "#c0392b",
        "accent_deep": "#8c231e",
        "bar": "linear-gradient(90deg,#8c231e,#c0392b,#2f7a3e)",
        "wash": "radial-gradient(closest-side,#fdeeec,#ffffff)",
        "chip_bg": "#f9ecea",
        "eyebrow": "原料嚴選 DSM 德國廠",
        "eyebrow_r": "全新升級加強版",
        "title": "高優質維他命B群",
        "subtitle": "一天一粒・60 粒軟膠囊",
        "hero": "bgroup",
        "hero_w": "600px",
        "chips": [
            ("60粒 軟膠囊", "#f9ecea", "#8c231e"),
            ("DSM 德國廠原料", "#f9ecea", "#8c231e"),
            ("95% 薑黃", "#fdf1e2", "#8a5410"),
        ],
        "usp_art": "bgroup",
        "usp_art_w": "380px",
        "usp_tag": "B GROUP",
        "usp": [
            ("原料嚴選 DSM 德國廠", "維生素原料來自 DSM 德國廠"),
            ("完整 B 群", "B1・B2・B6・B12、葉酸、生物素一次補足"),
            ("95% 薑黃・啤酒酵母・五味子", "加強版配方，複方協同"),
            ("一天一粒，方便持續", "軟膠囊好吞食，60 粒約一個月份"),
        ],
        "ing_title": "成分與規格",
        "ing_tag": "60 粒 軟膠囊",
        "ing": [
            ("維生素 B1・B2・B6・B12", "維生素群", True),
            ("葉酸・生物素", "維生素群", True),
            ("95% 薑黃萃取", "複方", True),
            ("啤酒酵母", "複方", True),
            ("五味子", "複方", True),
            ("規格", "60 粒 軟膠囊", True),
        ],
        "ing_art": "bgroup",
        "ing_art_bg": "#faf3f2",
        "note_bg": "#f9ecea",
        "note_fg": "#8c231e",
        "note_body_fg": "#7a3b35",
        "note_h": "建議食用方式",
        "note_p": "每日 1 粒，搭配溫水食用。",
        "company": "",
        "disclaimer": "注意事項：請置於陰涼乾燥處，避免高溫與陽光直射；開封後請儘早食用。",
    },
    {
        "slug": "coralca",
        "accent": "#1f6f9e",
        "accent_deep": "#134a6a",
        "bar": "linear-gradient(90deg,#134a6a,#3d9ac9,#c0392b)",
        "wash": "radial-gradient(closest-side,#e9f3f9,#ffffff)",
        "chip_bg": "#e6f1f8",
        "eyebrow": "MAGNESIUM GLYCINATE",
        "eyebrow_r": "MADE IN CANADA",
        "title": "甘鎂佳 珊瑚鈣",
        "subtitle": "MAGNESIUM GLYCINATE CORAL CA · K2(MK-7) ＋ D3 ＋ Mg",
        "hero": "coralca",
        "hero_w": "520px",
        "chips": [
            ("60錠/盒", "#e6f1f8", "#134a6a"),
            ("甘胺酸鎂", "#e6f1f8", "#134a6a"),
            ("加拿大製造", "#f9ecea", "#8c231e"),
        ],
        "usp_art": "coralca",
        "usp_art_w": "340px",
        "usp_tag": "CORAL CA",
        "usp": [
            ("珊瑚鈣 Coral Ca", "以珊瑚鈣為鈣質來源"),
            ("甘胺酸鎂 Magnesium Glycinate", "鎂與鈣搭配補充"),
            ("維生素 K2（MK-7）＋ D3", "K2 選用 MK-7 形式，搭配維生素 D3"),
            ("加拿大製造", "Made in Canada，60 錠裝"),
        ],
        "ing_title": "成分與規格",
        "ing_tag": "60 TABLETS",
        "ing": [
            ("珊瑚鈣", "Coral Ca", True),
            ("甘胺酸鎂", "Magnesium Glycinate", True),
            ("維生素 K2", "MK-7", True),
            ("維生素 D3", "D3", True),
            ("規格", "60 錠/盒", True),
            ("產地", "加拿大", True),
            ("品牌", "中旗生技", True),
        ],
        "ing_art": "coralca",
        "ing_art_bg": "#f2f7fa",
        "note_bg": "#e6f1f8",
        "note_fg": "#134a6a",
        "note_body_fg": "#2b5771",
        "note_h": "保存與提醒",
        "note_p": "請置於陰涼乾燥處，避免孩童自行取用。<br>孕婦及慢性病患者食用前請諮詢專業人員。",
        "company": "中旗生物科技股份有限公司",
        "disclaimer": "注意事項：",
    },
]
