"""電商產品圖的文案與版位資料。

內容照 Claude Design 專案「電商產品圖製作」的 電商產品圖.dc.html，數字一律回頭
對過實體包裝照與 `lib/data.ts`。與設計稿不同之處只有一處：設計稿把 DEFENSE 的
`company` 寫成「國鼎生物科技有限公司」，實際是「圓鼎」（包裝、data.ts 與店家
三方一致，2026-08-18 由店家確認）。

`asset` 為 None 代表素材還沒到位；版型會畫出明顯的缺件標記，不會靜默輸出空白圖。
"""

from __future__ import annotations

# 素材檔名 → 是否已備妥。缺的三張需要店家補原始照片。
MISSING_NOTE = {
    "defense-back": "缺 Defense 背面標示照",
    "yi-back": "缺 憶元素 營養標示照",
    "aob": "缺 AOB 商品照",
}

PRODUCTS = [
    {
        "slug": "defense",
        "accent": "#4d7c2a",
        "accent_deep": "#2f5417",
        "bar": "linear-gradient(90deg,#3d6420,#6ea23c,#e2953a)",
        "wash": "radial-gradient(closest-side,#f2f7ea,#ffffff)",
        "chip_bg": "#eef4e4",
        "eyebrow": "PUREGPS® 系列",
        "eyebrow_r": "植物膠囊・全素",
        "title": '強抗力優<sup>®</sup> 450⁺ 膠囊',
        "subtitle": "DEFENSE 450⁺ · β-1,3/1,6 GLUCO POLYSACCHARIDE",
        "hero": "defense-front",
        "hero_w": "600px",
        "chips": [
            ("60粒/盒・每粒450mg", "#eef4e4", "#2f5417"),
            ("Wellmune WGP® 原料", "#eef4e4", "#2f5417"),
            ("FDA APPROVED", "#fdf1e2", "#8a5410"),
        ],
        "usp_art": "defense-front",
        "usp_art_w": "360px",
        "usp_tag": "DEFENSE 450⁺",
        "usp": [
            ("高純度多醣體", "專利技術純化酵母，β-1,3/1,6 長鏈酵母葡聚多醣體純度高達 75% 以上"),
            ("國際原料授權", "採用 Wellmune WGP®，屬 Kerry 公司原料授權使用"),
            ("國際獲獎配方", "榮獲 2007 年 IFT 美國食品科學學會「創新研究獎」"),
            ("每天 1 顆，輕鬆保養", "每顆膠囊含 400mg β-1,3/1,6 酵母葡聚多醣體，天天食用防護周到"),
        ],
        "ing_row_pad": "17px",
        "ing_title": "成分與規格",
        "ing_tag": "每粒 450mg",
        "ing": [
            ("非水溶性葡聚多醣體", "250mg", False),
            ("水溶性葡聚多醣體", "150mg", False),
            ("穀胱甘肽", "50mg", False),
            ("植物膠囊基底", "纖維素・鹿角菜膠・氯化鉀", True),
            ("規格", "每盒 60 粒", True),
            ("產地", "台灣", True),
        ],
        "ing_art": None,          # defense-back 尚缺
        "ing_art_key": "defense-back",
        "ing_art_bg": "#f6f7f4",
        "note_bg": "#eef4e4",
        "note_fg": "#2f5417",
        "note_body_fg": "#3d5227",
        "note_h": "食用方法",
        "note_p": "每日 1~2 粒，餐後食用。請保存於陰涼乾燥處，避免熱及陽光直射。",
        "company": "圓鼎生物科技有限公司",
        "disclaimer": "注意事項：孕婦及授乳中婦女請遵照醫師指示食用；對穀胱甘肽過敏者、孕婦、哺乳婦女及嬰幼兒應避免食用。",
    },
    {
        "slug": "aob",
        "accent": "#3a8a7a",
        "accent_deep": "#23695c",
        "bar": "linear-gradient(90deg,#23695c,#6cc4b2,#b08d4f)",
        "wash": "radial-gradient(closest-side,#e9f6f2,#ffffff)",
        "chip_bg": "#e7f5f1",
        "eyebrow": "NEW · VITALITY BEAUTY",
        "eyebrow_r": "條狀隨身包",
        "title": "New AOB Vitality Beauty",
        "subtitle": "健全體調・美容增進",
        "hero": None,             # AOB 商品照尚缺
        "hero_key": "aob",
        "hero_w": "560px",
        "chips": [
            ("45包/盒", "#e7f5f1", "#23695c"),
            ("鋁袋條狀隨身包", "#e7f5f1", "#23695c"),
            ("NEW 配方", "#f5efe2", "#7c6230"),
        ],
        "usp_art": None,
        "usp_art_key": "aob",
        "usp_art_w": "400px",
        "usp_tag": "AOB",
        "usp_title": "產品特色與規格",
        "usp": [
            ("健全體調", "以日常保養為本，做好每天的健康打底"),
            ("美容增進", "內外兼顧，同時照顧美容保養需求"),
            ("45 包條狀隨身包", "單包分裝、免量取，通勤外出輕鬆帶著走"),
        ],
        "spec_table": [
            ("品名", "New AOB Vitality Beauty"),
            ("內容量", "45 包/盒"),
            ("包裝形式", "鋁袋條狀隨身包"),
        ],
        "screens": ["main", "usp"],
    },
    {
        "slug": "elgucare",
        "accent": "#24418f",
        "accent_deep": "#16295c",
        "bar": "linear-gradient(90deg,#16295c,#24418f,#bd2f28)",
        "wash": "radial-gradient(closest-side,#eef1f9,#ffffff)",
        "chip_bg": "#eaeff9",
        "eyebrow": "LHBcare® 綠杏",
        "eyebrow_r": "全素可食",
        "title": '綠杏 益固康<sup>®</sup> 膠囊',
        "subtitle": "ELGUCARE® · NEW TECHNIQUES OF NATURAL HERBAL FORMULAS",
        "hero": "elgucare-hero",
        "hero_h": "520px",
        "chips": [
            ("瓶裝 360粒", "#eaeff9", "#16295c"),
            ("盒裝 72粒・每粒600mg", "#eaeff9", "#16295c"),
            ("全素可食", "#e9f3e6", "#2f6323"),
            ("產地台灣", "#f9ecea", "#8c231e"),
        ],
        "usp_art": "elgucare-bottle",
        "usp_art_w": "340px",
        "usp_tag": "ELGUCARE®",
        "usp": [
            ("中醫藥專家研製", "集多年經驗，依人體生理機能需要特別研製的保健配方"),
            ("八種草本萃取複方", "黃耆・紅棗・丹參・雞屎藤・伸筋草・玉竹・紅景天・甘草"),
            ("生活挺立、能量豐沛", "日常保健，可讓生活挺立、豐沛人體能量"),
            ("全素可食", "素食者可安心食用，兩種容量規格自由選擇"),
        ],
        "ing_title": "成分與建議用量",
        "ing_tag": "每粒 600mg",
        "ing": [
            ("黃耆萃取", "210mg", False),
            ("紅棗萃取", "100mg", False),
            ("丹參萃取", "45mg", False),
            ("雞屎藤萃取", "35mg", False),
            ("伸筋草萃取", "35mg", False),
            ("玉竹萃取", "35mg", False),
            ("紅景天萃取", "20mg", False),
            ("甘草萃取", "20mg", False),
        ],
        "ing_art": "elgucare-box",
        "ing_art_bg": "#f5f6f8",
        "note_bg": "#eaeff9",
        "note_fg": "#16295c",
        "note_body_fg": "#2c3a5e",
        "note_h": "建議用量",
        "note_p": "保健：每日 2 次，每次 1~2 粒<br>加強：每日 2 次，每次 2~3 粒<br>飯前空腹食用最佳，多食無益",
        "company": "綠杏生物科技有限公司 總經銷",
        "disclaimer": "注意事項：避免孩童自行取用，請置於陰涼處、避免陽光直射。產地：台灣｜",
    },
    {
        "slug": "yiyuansu",
        "accent": "#b87c08",
        "accent_deep": "#7c5606",
        "bar": "linear-gradient(90deg,#b87c08,#eab52c,#2c4a9e)",
        "wash": "radial-gradient(closest-side,#fdf4dc,#ffffff)",
        "chip_bg": "#fdf3da",
        "eyebrow": "天麻100膠囊 · 食品",
        "eyebrow_r": "SGS 檢驗合格",
        "title": "憶元素 天麻100膠囊",
        "subtitle": "TIANMA 100 CAPSULES · 龍眼花+天麻雙萃取複方",
        "hero": "yi-front",
        "hero_w": "560px",
        "chips": [
            ("60粒/瓶", "#fdf3da", "#7c5606"),
            ("SGS 檢驗合格", "#fdf3da", "#7c5606"),
            ("含綜合維生素B群", "#e9eefb", "#22397c"),
        ],
        "usp_art": "yi-pair",
        "usp_art_w": "380px",
        "usp_tag": "天麻100",
        "usp": [
            ("龍眼花+天麻 雙萃取", "每粒含龍眼花萃取物 200mg、天麻萃取物 100mg"),
            ("綜合維生素B群 75mg", "B1・B2・B6・B12、菸鹼醯胺、葉酸、生物素"),
            ("蜂王乳・魚油・黑豆複方", "蜂王乳粉 50mg、魚油粉 30mg、黑豆粉 10mg"),
            ("SGS 檢驗合格", "品質把關，每日 1 粒、本包裝 60 份"),
        ],
        "ing_title": "成分與營養標示",
        "ing_tag": "每份 1 粒 · 60 份",
        "ing": [
            ("龍眼花萃取物", "200mg", False),
            ("天麻萃取物", "100mg", False),
            ("綜合維生素B群", "75mg", False),
            ("蜂王乳粉", "50mg", False),
            ("魚油粉", "30mg", False),
            ("黑豆粉", "10mg", False),
            ("維生素E粉", "5mg", False),
        ],
        "ing_art": None,          # yi-back 尚缺
        "ing_art_key": "yi-back",
        "ing_art_bg": "#f7f6f2",
        "note_bg": "#fdf3da",
        "note_fg": "#7c5606",
        "note_body_fg": "#6b5313",
        "note_h": "營養標示重點（每日參考值）",
        "note_p": "維生素B1 104%・B2 188%・B6 154%<br>葉酸 30 微克、生物素 3 微克",
        "company": "",
        "disclaimer": "注意事項：本品含乳糖、魚油、黑豆，對其成分過敏者請留意。請置於陰涼乾燥處，避免陽光直射。",
    },
]
